default: &default
  adapter: postgresql
  encoding: unicode
  username: luise
  password: luis123
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: safetech2_development

test:
  <<: *default
  database: safetech2_test

production:
  <<: *default
  database: safetech2_production
  username: safetech
  password: <%= ENV['SAFETECH_DATABASE_PASSWORD'] %>
